/*
 * text.h
 *
 * Created: 24Sep2013
 *  Author: chris.parker
 */ 

#ifndef TEXT_H_INCLUDED
#define TEXT_H_INCLUDED

//#include <asf.h>

/*
*	DEFINITIONS
**********************************************************/
//supported languages
typedef enum
{
	TEXT_LANGUAGE_ENGLISH,
	TEXT_LANGUAGE_SPANISH,
	TEXT_LANGUAGE_FRENCH,
	TEXT_LANGUAGE_PORTUGUESE,
	TEXT_LANGUAGE_GERMAN,
	TEXT_LANGUAGE_ITALIAN,
	//
	TEXT_NUM_LANGUAGES

} text_language_t;

//text list id's
//- each language's list should have an entry for each item here
//- if a message does not have a foreign language equivalent, use the
//  english version
typedef enum
{
	TEXT_ID_BLANK,
	TEXT_ID_EXIT,
	TEXT_ID_CANCEL,
	TEXT_ID_SELECT,
	TEXT_ID_BACK,
	TEXT_ID_EDIT,
	TEXT_ID_SAVE,
	TEXT_ID_SCROLL,
	TEXT_ID_PAGE,
	TEXT_ID_CLEAR,
	TEXT_ID_DELETE,
	TEXT_ID_RESET,
	TEXT_ID_YES,
	TEXT_ID_NO,
	TEXT_ID_OFF,
	TEXT_ID_ON,
	TEXT_ID_UP,
	TEXT_ID_DOWN,
	TEXT_ID_ADD,
	TEXT_ID_SET,
	TEXT_ID_MORE,
	TEXT_ID_LOG,
	TEXT_ID_LOCKOUT,
	TEXT_ID_LOW,
	TEXT_ID_HIGH,
	//
	TEXT_ID_MENU,
	TEXT_ID_CONFIGURATION,
	TEXT_ID_OPTIONS,
	TEXT_ID_SERVICE,
	TEXT_ID_HOURS,
	TEXT_ID_FAULTS,
	TEXT_ID_KEYS,
	TEXT_ID_SYSTEM,
	//
	TEXT_ID_BRAND,
	TEXT_ID_ADVANCE,
	TEXT_ID_NILFISK,
	//
	TEXT_ID_DECK_TYPE,
	TEXT_ID_DISC_34,
	TEXT_ID_DISC_40,
	TEXT_ID_CYL_36,
	//
	TEXT_ID_BATTERY_TYPE,
	TEXT_ID_WET,
	TEXT_ID_AGM,
	//
	TEXT_ID_OPT_PUMP,
	TEXT_ID_NONE,
	TEXT_ID_DUSTGUARD,
	TEXT_ID_SPRAYWASH,
	//
	TEXT_ID_VACUUM,
	TEXT_ID_SINGLE,
	TEXT_ID_DUAL,
	TEXT_ID_FULL,
	//
	TEXT_ID_SIDE_SWEEP,
	TEXT_ID_ECOFLEX,
	TEXT_ID_CHARGER,
	TEXT_ID_BACKUP_ALARM,
	TEXT_ID_HEADLIGHT,
	TEXT_ID_TRACKCLEAN,
	//
	TEXT_ID_LANGUAGE,
	TEXT_ID_ENGLISH,
	TEXT_ID_FRENCH,
	TEXT_ID_GERMAN,
	TEXT_ID_ITALIAN,
	TEXT_ID_PORTUGUESE,
	TEXT_ID_SPANISH,
	//
	TEXT_ID_FLOOR,
	TEXT_ID_STANDARD,
	TEXT_ID_SMOOTH,
	//
	TEXT_ID_SCRUB_START,
	TEXT_ID_LIGHT,
	TEXT_ID_HEAVY,
	TEXT_ID_EXTREME,
	TEXT_ID_LAST,
	//
	TEXT_ID_SCRUB_MAX,
	TEXT_ID_NEUTRAL_DELAY,
	TEXT_ID_VAC_OFF_DELAY,
	TEXT_ID_SOLUTION_IN_REVERSE,
	TEXT_ID_LOCK_DETERGENT,
	TEXT_ID_BOP_TIME,
	TEXT_ID_FWD_SPEED_MAX,
	TEXT_ID_LOCK_SPEED_LIMIT,
	TEXT_ID_INACTIVITY_TIMEOUT,
	TEXT_ID_IMPACT_DETECT,
	TEXT_ID_IMPACT_LEVEL,
	//
	TEXT_ID_SOLUTION,
	TEXT_ID_PROPORTIONAL,
	TEXT_ID_FIXED,
	TEXT_ID_UK,
	//
	TEXT_ID_E2_MAIN_CONTROLLER,
	TEXT_ID_E3_POWER_MODULE,
	TEXT_ID_E4_DRIVE_CONTROLLER,
	TEXT_ID_OUTPUT_TEST,
	TEXT_ID_PANEL_TEST,
	//
	TEXT_ID_FRONT_BRUSH,
	TEXT_ID_REAR_BRUSH,
	TEXT_ID_RIGHT_BRUSH,
	TEXT_ID_LEFT_BRUSH,
	TEXT_ID_SQUEEGEE,
	TEXT_ID_DECK,
	TEXT_ID_OPTION_PUMP,
	TEXT_ID_VOLTAGE,
	TEXT_ID_CURRENT,
	TEXT_ID_SPEED,
	TEXT_ID_THROTTLE,
	TEXT_ID_TEMPERATURE,
	TEXT_ID_TEMP_CUTBACK,
	//
	TEXT_ID_M1_CURRENT,
	TEXT_ID_M1_PWM,
	TEXT_ID_M1_DUTY_CYCLE,
	TEXT_ID_M2_CURRENT,
	TEXT_ID_M2_PWM,
	TEXT_ID_M2_DUTY_CYCLE,
	TEXT_ID_M3_CURRENT,
	TEXT_ID_M3_PWM,
	TEXT_ID_M3_DUTY_CYCLE,
	TEXT_ID_M4_CURRENT,
	TEXT_ID_M4_PWM,
	TEXT_ID_M4_DUTY_CYCLE,
	TEXT_ID_M5_CURRENT,
	TEXT_ID_M5_PWM,
	TEXT_ID_M5_DUTY_CYCLE,
	TEXT_ID_M6_CURRENT,
	TEXT_ID_M6_PWM,
	TEXT_ID_M6_DUTY_CYCLE,
	TEXT_ID_M7_CURRENT,
	TEXT_ID_M7_PWM,
	TEXT_ID_M7_DUTY_CYCLE,
	TEXT_ID_M10_CURRENT,
	TEXT_ID_M10_PWM,
	TEXT_ID_M10_DUTY_CYCLE,
	//
	TEXT_ID_ON_TIME,
	TEXT_ID_SCRUB_TIME,
	TEXT_ID_RECOVERY_TIME,
	TEXT_ID_DRIVE_TIME,
	//
	TEXT_ID_ACTIVE_FAULTS,
	TEXT_ID_FAULT_HISTORY,
	TEXT_ID_CLEAR_HISTORY,
	//
	TEXT_ID_READ_KEY,
	TEXT_ID_KEY_LIST,
	TEXT_ID_ADD_KEY,
	TEXT_ID_CLEAR_KEY_LIST,
	TEXT_ID_DELETE_KEY,
	TEXT_ID_INVALID_KEY,
	TEXT_ID_FAMILY,
	TEXT_ID_TYPE,
	TEXT_ID_USER,
	TEXT_ID_SUPERVISOR,
	TEXT_ID_TECHNICIAN,
	TEXT_ID_CALL,
	TEXT_ID_MAKE_SUPERVISOR,
	//
	TEXT_ID_FIRMWARE,
	TEXT_ID_SERIAL_NUM,
	TEXT_ID_INSTALL_FIRMWARE,
	TEXT_ID_INSERT_USB,
	TEXT_ID_FILE_NOT_FOUND,
	TEXT_ID_INVALID_FILE,
	TEXT_ID_FILE_ERROR,
	TEXT_ID_INSTALL,
	TEXT_ID_NEW_VERSION,
	TEXT_ID_LOADING,
	TEXT_ID_RESET_TO_INSTALL,
	//
	TEXT_ID_IMPACT_LOG,
	TEXT_ID_MAX,
	//
	//fault codes
	//----------------------------------
	//main fault codes
	TEXT_ID_FAULT_1_001,
	TEXT_ID_FAULT_1_002,
	TEXT_ID_FAULT_1_003,
	TEXT_ID_FAULT_1_010,
	TEXT_ID_FAULT_1_011,
	TEXT_ID_FAULT_1_101,
	TEXT_ID_FAULT_1_102,
	TEXT_ID_FAULT_1_103,
	TEXT_ID_FAULT_1_104,
	TEXT_ID_FAULT_1_105,
	TEXT_ID_FAULT_1_106,
	TEXT_ID_FAULT_1_107,
	TEXT_ID_FAULT_1_201,
	TEXT_ID_FAULT_1_560,
	TEXT_ID_FAULT_1_561,
	TEXT_ID_FAULT_1_562,
	TEXT_ID_FAULT_1_563,
	TEXT_ID_FAULT_1_564,
	TEXT_ID_FAULT_1_565,
	TEXT_ID_FAULT_1_566,
	//curtis 1355 power module fault codes
	TEXT_ID_FAULT_2_001,
	TEXT_ID_FAULT_2_011,
	TEXT_ID_FAULT_2_012,
	TEXT_ID_FAULT_2_013,
	TEXT_ID_FAULT_2_014,
	TEXT_ID_FAULT_2_015,
	TEXT_ID_FAULT_2_016,
	TEXT_ID_FAULT_2_017,
	TEXT_ID_FAULT_2_018,
	TEXT_ID_FAULT_2_021,
	TEXT_ID_FAULT_2_022,
	TEXT_ID_FAULT_2_023,
	TEXT_ID_FAULT_2_024,
	TEXT_ID_FAULT_2_025,
	TEXT_ID_FAULT_2_026,
	TEXT_ID_FAULT_2_027,
	TEXT_ID_FAULT_2_028,
	TEXT_ID_FAULT_2_031,
	TEXT_ID_FAULT_2_032,
	TEXT_ID_FAULT_2_033,
	TEXT_ID_FAULT_2_034,
	TEXT_ID_FAULT_2_035,
	TEXT_ID_FAULT_2_036,
	TEXT_ID_FAULT_2_037,
	TEXT_ID_FAULT_2_038,
	TEXT_ID_FAULT_2_041,
	TEXT_ID_FAULT_2_042,
	TEXT_ID_FAULT_2_043,
	TEXT_ID_FAULT_2_044,
	TEXT_ID_FAULT_2_045,
	TEXT_ID_FAULT_2_046,
	TEXT_ID_FAULT_2_047,
	TEXT_ID_FAULT_2_048,
	TEXT_ID_FAULT_2_051,
	TEXT_ID_FAULT_2_052,
	TEXT_ID_FAULT_2_053,
	TEXT_ID_FAULT_2_054,
	TEXT_ID_FAULT_2_055,
	TEXT_ID_FAULT_2_056,
	TEXT_ID_FAULT_2_057,
	TEXT_ID_FAULT_2_058,
	TEXT_ID_FAULT_2_061,
	TEXT_ID_FAULT_2_062,
	TEXT_ID_FAULT_2_063,
	TEXT_ID_FAULT_2_064,
	TEXT_ID_FAULT_2_065,
	TEXT_ID_FAULT_2_066,
	TEXT_ID_FAULT_2_067,
	TEXT_ID_FAULT_2_071,
	TEXT_ID_FAULT_2_072,
	TEXT_ID_FAULT_2_073,
	TEXT_ID_FAULT_2_074,
	TEXT_ID_FAULT_2_075,
	TEXT_ID_FAULT_2_076,
	TEXT_ID_FAULT_2_077,
	TEXT_ID_FAULT_2_078,
	TEXT_ID_FAULT_2_081,
	TEXT_ID_FAULT_2_082,
	TEXT_ID_FAULT_2_083,
	TEXT_ID_FAULT_2_084,
	TEXT_ID_FAULT_2_086,
	TEXT_ID_FAULT_2_087,
	TEXT_ID_FAULT_2_088,
	TEXT_ID_FAULT_2_091,
	TEXT_ID_FAULT_2_092,
	TEXT_ID_FAULT_2_093,
	TEXT_ID_FAULT_2_094,
	TEXT_ID_FAULT_2_095,
	TEXT_ID_FAULT_2_096,
	TEXT_ID_FAULT_2_097,
	TEXT_ID_FAULT_2_098,
	TEXT_ID_FAULT_2_101,
	TEXT_ID_FAULT_2_102,
	TEXT_ID_FAULT_2_103,
	//curtis 1232e drive controller fault codes
	TEXT_ID_FAULT_3_001,
	TEXT_ID_FAULT_3_038,
	TEXT_ID_FAULT_3_039,
	TEXT_ID_FAULT_3_045,
	TEXT_ID_FAULT_3_042,
	TEXT_ID_FAULT_3_041,
	TEXT_ID_FAULT_3_044,
	TEXT_ID_FAULT_3_043,
	TEXT_ID_FAULT_3_046,
	TEXT_ID_FAULT_3_047,
	TEXT_ID_FAULT_3_017,
	TEXT_ID_FAULT_3_018,
	TEXT_ID_FAULT_3_023,
	TEXT_ID_FAULT_3_024,
	TEXT_ID_FAULT_3_022,
	TEXT_ID_FAULT_3_015,
	TEXT_ID_FAULT_3_016,
	TEXT_ID_FAULT_3_031,
	TEXT_ID_FAULT_3_032,
	TEXT_ID_FAULT_3_014,
	TEXT_ID_FAULT_3_012,
	TEXT_ID_FAULT_3_013,
	TEXT_ID_FAULT_3_028,
	TEXT_ID_FAULT_3_049,
	TEXT_ID_FAULT_3_037,
	TEXT_ID_FAULT_3_069,
	TEXT_ID_FAULT_3_029,
	TEXT_ID_FAULT_3_068,
	TEXT_ID_FAULT_3_025,
	TEXT_ID_FAULT_3_071,
	TEXT_ID_FAULT_3_072,
	TEXT_ID_FAULT_3_036,
	TEXT_ID_FAULT_3_073,
	TEXT_ID_FAULT_3_089,
	TEXT_ID_FAULT_3_077,
	TEXT_ID_FAULT_3_087,
	TEXT_ID_FAULT_3_091,
	TEXT_ID_FAULT_3_092,
	TEXT_ID_FAULT_3_093,
	TEXT_ID_FAULT_3_088,
	TEXT_ID_FAULT_3_078,
	TEXT_ID_FAULT_3_051,
	TEXT_ID_FAULT_3_056,
	TEXT_ID_FAULT_3_057,
	//	
	
	//this must be last !!
	TEXT_LIST_SIZE
	
} text_id_t;

//NOTE:
//the currently selected language is stored in parameters

/*
*	VARIABLES
**********************************************************/
//message lists for supported languages
extern const char* gk_textListEnglish[TEXT_LIST_SIZE];
extern const char* gk_textListSpanish[TEXT_LIST_SIZE];
extern const char* gk_textListFrench[TEXT_LIST_SIZE];
extern const char* gk_textListPortuguese[TEXT_LIST_SIZE];
extern const char* gk_textListGerman[TEXT_LIST_SIZE];
extern const char* gk_textListItalian[TEXT_LIST_SIZE];

/*
*			PROTOTYPES
**********************************************************/
//set the language
void Text_SetLanguage (text_language_t language);
//get text string from the list
const char* Text_Get (text_id_t id);


#endif /* TEXT_H_INCLUDED */